load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "views",
    srcs = [
        "landing_viewmodel.go",
        "table_viewmodel.go",
        "view.go",
    ],
    importpath = "github.com/google/taxinomia/core/views",
    visibility = ["//visibility:public"],
    deps = [
        "//core/aggregates",
        "//core/columns",
        "//core/grouping",
        "//core/models",
        "//core/query",
        "//core/tables",
        "@com_github_google_safehtml//:safehtml",
    ],
)
