// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2024 The Taxinomia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: core/csvimport/proto/table_annotation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnType specifies the data type for a column.
type ColumnType int32

const (
	// Auto-detect type from data (default).
	ColumnType_COLUMN_TYPE_AUTO ColumnType = 0
	// String column.
	ColumnType_COLUMN_TYPE_STRING ColumnType = 1
	// Unsigned 32-bit integer column.
	ColumnType_COLUMN_TYPE_UINT32 ColumnType = 2
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_AUTO",
		1: "COLUMN_TYPE_STRING",
		2: "COLUMN_TYPE_UINT32",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_AUTO":   0,
		"COLUMN_TYPE_STRING": 1,
		"COLUMN_TYPE_UINT32": 2,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_csvimport_proto_table_annotation_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_core_csvimport_proto_table_annotation_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_core_csvimport_proto_table_annotation_proto_rawDescGZIP(), []int{0}
}

// ColumnAnnotation defines annotations for a single CSV column.
type ColumnAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The column name in the CSV header (required for matching).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in the UI. If empty, uses the CSV header name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Entity type for join support (e.g., "region", "category").
	// Columns with matching entity types across tables can be joined.
	EntityType string `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// Data type for this column. If AUTO, type is detected from data.
	Type          ColumnType `protobuf:"varint,4,opt,name=type,proto3,enum=taxinomia.csvimport.ColumnType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnAnnotation) Reset() {
	*x = ColumnAnnotation{}
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnAnnotation) ProtoMessage() {}

func (x *ColumnAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnAnnotation.ProtoReflect.Descriptor instead.
func (*ColumnAnnotation) Descriptor() ([]byte, []int) {
	return file_core_csvimport_proto_table_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnAnnotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnAnnotation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ColumnAnnotation) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ColumnAnnotation) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_AUTO
}

// TableAnnotation defines annotations for importing a CSV file as a table.
type TableAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the table.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Annotations for individual columns.
	Columns []*ColumnAnnotation `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Domains group related tables together (e.g., "demo", "sales", "inventory").
	// A table can belong to multiple domains.
	Domains       []string `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableAnnotation) Reset() {
	*x = TableAnnotation{}
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAnnotation) ProtoMessage() {}

func (x *TableAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAnnotation.ProtoReflect.Descriptor instead.
func (*TableAnnotation) Descriptor() ([]byte, []int) {
	return file_core_csvimport_proto_table_annotation_proto_rawDescGZIP(), []int{1}
}

func (x *TableAnnotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableAnnotation) GetColumns() []*ColumnAnnotation {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableAnnotation) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// TableAnnotations is a collection of table annotations.
type TableAnnotations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of table annotations.
	Tables        []*TableAnnotation `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableAnnotations) Reset() {
	*x = TableAnnotations{}
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAnnotations) ProtoMessage() {}

func (x *TableAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_proto_table_annotation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAnnotations.ProtoReflect.Descriptor instead.
func (*TableAnnotations) Descriptor() ([]byte, []int) {
	return file_core_csvimport_proto_table_annotation_proto_rawDescGZIP(), []int{2}
}

func (x *TableAnnotations) GetTables() []*TableAnnotation {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_core_csvimport_proto_table_annotation_proto protoreflect.FileDescriptor

const file_core_csvimport_proto_table_annotation_proto_rawDesc = "" +
	"\n" +
	"+core/csvimport/proto/table_annotation.proto\x12\x13taxinomia.csvimport\"\x9f\x01\n" +
	"\x10ColumnAnnotation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.taxinomia.csvimport.ColumnTypeR\x04type\"\x80\x01\n" +
	"\x0fTableAnnotation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\acolumns\x18\x02 \x03(\v2%.taxinomia.csvimport.ColumnAnnotationR\acolumns\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\"P\n" +
	"\x10TableAnnotations\x12<\n" +
	"\x06tables\x18\x01 \x03(\v2$.taxinomia.csvimport.TableAnnotationR\x06tables*R\n" +
	"\n" +
	"ColumnType\x12\x14\n" +
	"\x10COLUMN_TYPE_AUTO\x10\x00\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12COLUMN_TYPE_UINT32\x10\x02B2Z0github.com/google/taxinomia/core/csvimport/protob\x06proto3"

var (
	file_core_csvimport_proto_table_annotation_proto_rawDescOnce sync.Once
	file_core_csvimport_proto_table_annotation_proto_rawDescData []byte
)

func file_core_csvimport_proto_table_annotation_proto_rawDescGZIP() []byte {
	file_core_csvimport_proto_table_annotation_proto_rawDescOnce.Do(func() {
		file_core_csvimport_proto_table_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_csvimport_proto_table_annotation_proto_rawDesc), len(file_core_csvimport_proto_table_annotation_proto_rawDesc)))
	})
	return file_core_csvimport_proto_table_annotation_proto_rawDescData
}

var file_core_csvimport_proto_table_annotation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_csvimport_proto_table_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_csvimport_proto_table_annotation_proto_goTypes = []any{
	(ColumnType)(0),          // 0: taxinomia.csvimport.ColumnType
	(*ColumnAnnotation)(nil), // 1: taxinomia.csvimport.ColumnAnnotation
	(*TableAnnotation)(nil),  // 2: taxinomia.csvimport.TableAnnotation
	(*TableAnnotations)(nil), // 3: taxinomia.csvimport.TableAnnotations
}
var file_core_csvimport_proto_table_annotation_proto_depIdxs = []int32{
	0, // 0: taxinomia.csvimport.ColumnAnnotation.type:type_name -> taxinomia.csvimport.ColumnType
	1, // 1: taxinomia.csvimport.TableAnnotation.columns:type_name -> taxinomia.csvimport.ColumnAnnotation
	2, // 2: taxinomia.csvimport.TableAnnotations.tables:type_name -> taxinomia.csvimport.TableAnnotation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_csvimport_proto_table_annotation_proto_init() }
func file_core_csvimport_proto_table_annotation_proto_init() {
	if File_core_csvimport_proto_table_annotation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_csvimport_proto_table_annotation_proto_rawDesc), len(file_core_csvimport_proto_table_annotation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_csvimport_proto_table_annotation_proto_goTypes,
		DependencyIndexes: file_core_csvimport_proto_table_annotation_proto_depIdxs,
		EnumInfos:         file_core_csvimport_proto_table_annotation_proto_enumTypes,
		MessageInfos:      file_core_csvimport_proto_table_annotation_proto_msgTypes,
	}.Build()
	File_core_csvimport_proto_table_annotation_proto = out.File
	file_core_csvimport_proto_table_annotation_proto_goTypes = nil
	file_core_csvimport_proto_table_annotation_proto_depIdxs = nil
}
