load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "columns",
    srcs = [
        "bool_column.go",
        "columns.go",
        "compare.go",
        "computed_columns.go",
        "datetime_column.go",
        "dict_column.go",
        "duration_column.go",
        "float64_column.go",
        "group_ops.go",
        "int64_column.go",
        "joined_columns.go",
        "string_column.go",
        "uint32_column.go",
        "uint64_column.go",
    ],
    importpath = "github.com/google/taxinomia/core/columns",
    visibility = ["//visibility:public"],
)

go_test(
    name = "columns_test",
    srcs = [
        "column_bench_test.go",
        "datetime_column_test.go",
        "dict_cardinality_test.go",
        "dict_column_bench_test.go",
        "dict_column_test.go",
        "duration_column_test.go",
        "group_ops_test.go",
    ],
    embed = [":columns"],
)
