load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "buildinfo",
    srcs = [
        "buildinfo.go",
        "version.go",
    ],
    importpath = "github.com/google/taxinomia/core/buildinfo",
    visibility = ["//visibility:public"],
)

go_test(
    name = "buildinfo_test",
    srcs = ["buildinfo_test.go"],
    embed = [":buildinfo"],
)
