// Code generated by tools/hooks/pre-commit; DO NOT EDIT.

package buildinfo

// Revision of the source tree, recorded at commit time: the commit count
// and commit date of the revision this file was committed in. This is what
// importers of the library display; the link-time stamp (when present)
// overrides it and adds the commit hash and dirty flag.
const (
	sourceRevision = "170"
	sourceDate     = "2026-09-06"
)
