// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2024 The Taxinomia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: core/csvimport/table_source.proto

package csvimport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnType specifies the data type for a column.
type ColumnType int32

const (
	// Auto-detect type from data (default).
	ColumnType_COLUMN_TYPE_AUTO ColumnType = 0
	// String column.
	ColumnType_COLUMN_TYPE_STRING ColumnType = 1
	// Unsigned 32-bit integer column.
	ColumnType_COLUMN_TYPE_UINT32 ColumnType = 2
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_AUTO",
		1: "COLUMN_TYPE_STRING",
		2: "COLUMN_TYPE_UINT32",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_AUTO":   0,
		"COLUMN_TYPE_STRING": 1,
		"COLUMN_TYPE_UINT32": 2,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_csvimport_table_source_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_core_csvimport_table_source_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_core_csvimport_table_source_proto_rawDescGZIP(), []int{0}
}

// ColumnSource defines source metadata for a single CSV column.
type ColumnSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The column name in the CSV header (required for matching).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in the UI. If empty, uses the CSV header name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Entity type for join support (e.g., "region", "category").
	// Columns with matching entity types across tables can be joined.
	EntityType string `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// Data type for this column. If AUTO, type is detected from data.
	Type          ColumnType `protobuf:"varint,4,opt,name=type,proto3,enum=taxinomia.csvimport.ColumnType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnSource) Reset() {
	*x = ColumnSource{}
	mi := &file_core_csvimport_table_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnSource) ProtoMessage() {}

func (x *ColumnSource) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_table_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnSource.ProtoReflect.Descriptor instead.
func (*ColumnSource) Descriptor() ([]byte, []int) {
	return file_core_csvimport_table_source_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnSource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ColumnSource) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ColumnSource) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_AUTO
}

// TableSource defines source metadata for importing a CSV file as a table.
type TableSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the table.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Source metadata for individual columns.
	Columns []*ColumnSource `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Domains group related tables together (e.g., "demo", "sales", "inventory").
	// A table can belong to multiple domains.
	Domains []string `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	// CSV file name (e.g., "orders.csv").
	CsvFile       string `protobuf:"bytes,4,opt,name=csv_file,json=csvFile,proto3" json:"csv_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSource) Reset() {
	*x = TableSource{}
	mi := &file_core_csvimport_table_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSource) ProtoMessage() {}

func (x *TableSource) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_table_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSource.ProtoReflect.Descriptor instead.
func (*TableSource) Descriptor() ([]byte, []int) {
	return file_core_csvimport_table_source_proto_rawDescGZIP(), []int{1}
}

func (x *TableSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSource) GetColumns() []*ColumnSource {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableSource) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *TableSource) GetCsvFile() string {
	if x != nil {
		return x.CsvFile
	}
	return ""
}

// TableSources is a collection of table sources.
type TableSources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of table sources.
	Tables        []*TableSource `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSources) Reset() {
	*x = TableSources{}
	mi := &file_core_csvimport_table_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSources) ProtoMessage() {}

func (x *TableSources) ProtoReflect() protoreflect.Message {
	mi := &file_core_csvimport_table_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSources.ProtoReflect.Descriptor instead.
func (*TableSources) Descriptor() ([]byte, []int) {
	return file_core_csvimport_table_source_proto_rawDescGZIP(), []int{2}
}

func (x *TableSources) GetTables() []*TableSource {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_core_csvimport_table_source_proto protoreflect.FileDescriptor

const file_core_csvimport_table_source_proto_rawDesc = "" +
	"\n" +
	"!core/csvimport/table_source.proto\x12\x13taxinomia.csvimport\"\x9b\x01\n" +
	"\fColumnSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.taxinomia.csvimport.ColumnTypeR\x04type\"\x93\x01\n" +
	"\vTableSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\acolumns\x18\x02 \x03(\v2!.taxinomia.csvimport.ColumnSourceR\acolumns\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12\x19\n" +
	"\bcsv_file\x18\x04 \x01(\tR\acsvFile\"H\n" +
	"\fTableSources\x128\n" +
	"\x06tables\x18\x01 \x03(\v2 .taxinomia.csvimport.TableSourceR\x06tables*R\n" +
	"\n" +
	"ColumnType\x12\x14\n" +
	"\x10COLUMN_TYPE_AUTO\x10\x00\x12\x16\n" +
	"\x12COLUMN_TYPE_STRING\x10\x01\x12\x16\n" +
	"\x12COLUMN_TYPE_UINT32\x10\x02B,Z*github.com/google/taxinomia/core/csvimportb\x06proto3"

var (
	file_core_csvimport_table_source_proto_rawDescOnce sync.Once
	file_core_csvimport_table_source_proto_rawDescData []byte
)

func file_core_csvimport_table_source_proto_rawDescGZIP() []byte {
	file_core_csvimport_table_source_proto_rawDescOnce.Do(func() {
		file_core_csvimport_table_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_csvimport_table_source_proto_rawDesc), len(file_core_csvimport_table_source_proto_rawDesc)))
	})
	return file_core_csvimport_table_source_proto_rawDescData
}

var file_core_csvimport_table_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_csvimport_table_source_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_csvimport_table_source_proto_goTypes = []any{
	(ColumnType)(0),      // 0: taxinomia.csvimport.ColumnType
	(*ColumnSource)(nil), // 1: taxinomia.csvimport.ColumnSource
	(*TableSource)(nil),  // 2: taxinomia.csvimport.TableSource
	(*TableSources)(nil), // 3: taxinomia.csvimport.TableSources
}
var file_core_csvimport_table_source_proto_depIdxs = []int32{
	0, // 0: taxinomia.csvimport.ColumnSource.type:type_name -> taxinomia.csvimport.ColumnType
	1, // 1: taxinomia.csvimport.TableSource.columns:type_name -> taxinomia.csvimport.ColumnSource
	2, // 2: taxinomia.csvimport.TableSources.tables:type_name -> taxinomia.csvimport.TableSource
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_csvimport_table_source_proto_init() }
func file_core_csvimport_table_source_proto_init() {
	if File_core_csvimport_table_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_csvimport_table_source_proto_rawDesc), len(file_core_csvimport_table_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_csvimport_table_source_proto_goTypes,
		DependencyIndexes: file_core_csvimport_table_source_proto_depIdxs,
		EnumInfos:         file_core_csvimport_table_source_proto_enumTypes,
		MessageInfos:      file_core_csvimport_table_source_proto_msgTypes,
	}.Build()
	File_core_csvimport_table_source_proto = out.File
	file_core_csvimport_table_source_proto_goTypes = nil
	file_core_csvimport_table_source_proto_depIdxs = nil
}
