load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "handlers",
    srcs = ["server.go"],
    importpath = "github.com/google/taxinomia/web/handlers",
    visibility = [
        "//core/query:__pkg__",
        "//core/rendering:__pkg__",
        "//core/server:__pkg__",
        "//core/views:__pkg__",
        "//demo:__pkg__",
        "//web:__subpackages__",
    ],
    deps = [
        "//core/columns",
        "//core/engine",
        "//core/expr",
        "//core/models",
        "//core/tables",
        "//core/users",
        "//web/navigation",
        "//web/rendering",
        "//web/urlquery",
        "//web/viewmodel",
    ],
)
