// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2024 The Taxinomia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: core/users/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfile defines a user's preferences and access configuration.
// The username is derived from the folder name containing the profile.
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domains the user has access to.
	// Only tables belonging to these domains will be visible.
	Domains       []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_core_users_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_core_users_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_core_users_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_core_users_proto_user_proto protoreflect.FileDescriptor

const file_core_users_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/users/proto/user.proto\x12\x0ftaxinomia.users\"'\n" +
	"\vUserProfile\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomainsB.Z,github.com/google/taxinomia/core/users/protob\x06proto3"

var (
	file_core_users_proto_user_proto_rawDescOnce sync.Once
	file_core_users_proto_user_proto_rawDescData []byte
)

func file_core_users_proto_user_proto_rawDescGZIP() []byte {
	file_core_users_proto_user_proto_rawDescOnce.Do(func() {
		file_core_users_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_users_proto_user_proto_rawDesc), len(file_core_users_proto_user_proto_rawDesc)))
	})
	return file_core_users_proto_user_proto_rawDescData
}

var file_core_users_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_users_proto_user_proto_goTypes = []any{
	(*UserProfile)(nil), // 0: taxinomia.users.UserProfile
}
var file_core_users_proto_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_users_proto_user_proto_init() }
func file_core_users_proto_user_proto_init() {
	if File_core_users_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_users_proto_user_proto_rawDesc), len(file_core_users_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_users_proto_user_proto_goTypes,
		DependencyIndexes: file_core_users_proto_user_proto_depIdxs,
		MessageInfos:      file_core_users_proto_user_proto_msgTypes,
	}.Build()
	File_core_users_proto_user_proto = out.File
	file_core_users_proto_user_proto_goTypes = nil
	file_core_users_proto_user_proto_depIdxs = nil
}
