load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "viewmodel",
    srcs = [
        "landing_viewmodel.go",
        "format.go",
        "table_viewmodel.go",
        "view.go",
    ],
    importpath = "github.com/google/taxinomia/web/viewmodel",
    visibility = [
        "//core/query:__pkg__",
        "//core/rendering:__pkg__",
        "//core/server:__pkg__",
        "//core/views:__pkg__",
        "//demo:__pkg__",
        "//web:__subpackages__",
    ],
    deps = [
        "//core/aggregates",
        "//core/buildinfo",
        "//core/columns",
        "//core/grouping",
        "//core/models",
        "//core/queryspec",
        "//core/tables",
        "//web/urlquery",
        "@com_github_google_safehtml//:safehtml",
    ],
)
