// SPDX-License-Identifier: Apache-2.0
//
// Copyright 2024 The Taxinomia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: datasource.proto

package datasources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnAnnotation defines UI and join metadata for a column.
// This is NOT the column schema (name, type) - that comes from the data source itself
// (proto descriptor, database schema, CSV header, etc.).
type ColumnAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The column name (must match the actual column name from the data source).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in the UI. If empty, uses the column name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Entity type for join support (e.g., "customer_id", "order_id").
	// Columns with matching entity types across tables can be joined.
	EntityType    string `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnAnnotation) Reset() {
	*x = ColumnAnnotation{}
	mi := &file_datasource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnAnnotation) ProtoMessage() {}

func (x *ColumnAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnAnnotation.ProtoReflect.Descriptor instead.
func (*ColumnAnnotation) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnAnnotation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnAnnotation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ColumnAnnotation) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

// ColumnAnnotations defines annotations for columns in a data source.
// The actual column schema (names, types) is discovered from the data source;
// these annotations add display names and entity types on top.
type ColumnAnnotations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this annotation set (e.g., proto message type, table name).
	AnnotationsId string `protobuf:"bytes,1,opt,name=annotations_id,json=annotationsId,proto3" json:"annotations_id,omitempty"`
	// Column annotations. Only columns listed here have their metadata overridden;
	// unlisted columns use defaults (column name as display name, no entity type).
	Columns       []*ColumnAnnotation `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnAnnotations) Reset() {
	*x = ColumnAnnotations{}
	mi := &file_datasource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnAnnotations) ProtoMessage() {}

func (x *ColumnAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnAnnotations.ProtoReflect.Descriptor instead.
func (*ColumnAnnotations) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnAnnotations) GetAnnotationsId() string {
	if x != nil {
		return x.AnnotationsId
	}
	return ""
}

func (x *ColumnAnnotations) GetColumns() []*ColumnAnnotation {
	if x != nil {
		return x.Columns
	}
	return nil
}

// DataSource defines a single data source.
type DataSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the table in the data model.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// References a ColumnAnnotations by annotations_id.
	// The actual schema comes from the data source (descriptor, database, etc.).
	AnnotationsId string `protobuf:"bytes,2,opt,name=annotations_id,json=annotationsId,proto3" json:"annotations_id,omitempty"`
	// Domains group related tables together (e.g., "demo", "sales").
	Domains []string `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	// Source type identifier - looked up in the loader registry.
	// Built-in types: "proto", "csv"
	// Users can register custom types: "postgres", "bigquery", etc.
	SourceType string `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Type-specific configuration as key-value pairs.
	// Each loader defines its own required/optional config keys.
	Config map[string]string `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The entity type that serves as this table's primary key.
	// This identifies the main entity type that this table is about.
	// For example: "region" for a regions table, "customer_id" for a customers table.
	PrimaryKeyEntityType string `protobuf:"bytes,6,opt,name=primary_key_entity_type,json=primaryKeyEntityType,proto3" json:"primary_key_entity_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataSource) Reset() {
	*x = DataSource{}
	mi := &file_datasource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSource) ProtoMessage() {}

func (x *DataSource) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSource.ProtoReflect.Descriptor instead.
func (*DataSource) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{2}
}

func (x *DataSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSource) GetAnnotationsId() string {
	if x != nil {
		return x.AnnotationsId
	}
	return ""
}

func (x *DataSource) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DataSource) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DataSource) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DataSource) GetPrimaryKeyEntityType() string {
	if x != nil {
		return x.PrimaryKeyEntityType
	}
	return ""
}

// URLTemplate defines a single URL template with a display name.
// Templates can use placeholders like {value}, {column}, {table}.
type URLTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name shown in the UI (e.g., "View Product", "Filter by Customer").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL template with placeholders (e.g., "/table?table=orders&filter=customer_id:{value}").
	Template string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// If true, this URL is used as the default link for cell values.
	// Only one URL per entity type should be marked as default.
	// If no URL is marked as default, the first URL is used.
	IsDefault     bool `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLTemplate) Reset() {
	*x = URLTemplate{}
	mi := &file_datasource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLTemplate) ProtoMessage() {}

func (x *URLTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLTemplate.ProtoReflect.Descriptor instead.
func (*URLTemplate) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{3}
}

func (x *URLTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *URLTemplate) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *URLTemplate) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// EntityTypeDefinition defines metadata for an entity type.
// Entity types enable joins between columns and can have associated URL templates.
type EntityTypeDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entity type name (e.g., "demo.customer_id", "meta.table_name").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of this entity type.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// URL templates for navigating to related views.
	// Multiple templates allow different actions (view, edit, filter, etc.).
	Urls          []*URLTemplate `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityTypeDefinition) Reset() {
	*x = EntityTypeDefinition{}
	mi := &file_datasource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityTypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityTypeDefinition) ProtoMessage() {}

func (x *EntityTypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityTypeDefinition.ProtoReflect.Descriptor instead.
func (*EntityTypeDefinition) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{4}
}

func (x *EntityTypeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityTypeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntityTypeDefinition) GetUrls() []*URLTemplate {
	if x != nil {
		return x.Urls
	}
	return nil
}

// DataSourcesConfig is the top-level configuration for data sources.
type DataSourcesConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column annotations - loaded eagerly at startup.
	// The actual schema is discovered when loading each data source.
	Annotations []*ColumnAnnotations `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	// Data sources - metadata only, data loaded lazily on demand.
	Sources []*DataSource `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	// Entity type definitions with descriptions and URL templates.
	EntityTypes   []*EntityTypeDefinition `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSourcesConfig) Reset() {
	*x = DataSourcesConfig{}
	mi := &file_datasource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourcesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourcesConfig) ProtoMessage() {}

func (x *DataSourcesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_datasource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourcesConfig.ProtoReflect.Descriptor instead.
func (*DataSourcesConfig) Descriptor() ([]byte, []int) {
	return file_datasource_proto_rawDescGZIP(), []int{5}
}

func (x *DataSourcesConfig) GetAnnotations() []*ColumnAnnotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *DataSourcesConfig) GetSources() []*DataSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *DataSourcesConfig) GetEntityTypes() []*EntityTypeDefinition {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

var File_datasource_proto protoreflect.FileDescriptor

const file_datasource_proto_rawDesc = "" +
	"\n" +
	"\x10datasource.proto\x12\x15taxinomia.datasources\"j\n" +
	"\x10ColumnAnnotation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\"}\n" +
	"\x11ColumnAnnotations\x12%\n" +
	"\x0eannotations_id\x18\x01 \x01(\tR\rannotationsId\x12A\n" +
	"\acolumns\x18\x02 \x03(\v2'.taxinomia.datasources.ColumnAnnotationR\acolumns\"\xbb\x02\n" +
	"\n" +
	"DataSource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eannotations_id\x18\x02 \x01(\tR\rannotationsId\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12E\n" +
	"\x06config\x18\x05 \x03(\v2-.taxinomia.datasources.DataSource.ConfigEntryR\x06config\x125\n" +
	"\x17primary_key_entity_type\x18\x06 \x01(\tR\x14primaryKeyEntityType\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\vURLTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\"\x84\x01\n" +
	"\x14EntityTypeDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\x04urls\x18\x03 \x03(\v2\".taxinomia.datasources.URLTemplateR\x04urls\"\xec\x01\n" +
	"\x11DataSourcesConfig\x12J\n" +
	"\vannotations\x18\x01 \x03(\v2(.taxinomia.datasources.ColumnAnnotationsR\vannotations\x12;\n" +
	"\asources\x18\x02 \x03(\v2!.taxinomia.datasources.DataSourceR\asources\x12N\n" +
	"\fentity_types\x18\x03 \x03(\v2+.taxinomia.datasources.EntityTypeDefinitionR\ventityTypesB)Z'github.com/google/taxinomia/datasourcesb\x06proto3"

var (
	file_datasource_proto_rawDescOnce sync.Once
	file_datasource_proto_rawDescData []byte
)

func file_datasource_proto_rawDescGZIP() []byte {
	file_datasource_proto_rawDescOnce.Do(func() {
		file_datasource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)))
	})
	return file_datasource_proto_rawDescData
}

var file_datasource_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_datasource_proto_goTypes = []any{
	(*ColumnAnnotation)(nil),     // 0: taxinomia.datasources.ColumnAnnotation
	(*ColumnAnnotations)(nil),    // 1: taxinomia.datasources.ColumnAnnotations
	(*DataSource)(nil),           // 2: taxinomia.datasources.DataSource
	(*URLTemplate)(nil),          // 3: taxinomia.datasources.URLTemplate
	(*EntityTypeDefinition)(nil), // 4: taxinomia.datasources.EntityTypeDefinition
	(*DataSourcesConfig)(nil),    // 5: taxinomia.datasources.DataSourcesConfig
	nil,                          // 6: taxinomia.datasources.DataSource.ConfigEntry
}
var file_datasource_proto_depIdxs = []int32{
	0, // 0: taxinomia.datasources.ColumnAnnotations.columns:type_name -> taxinomia.datasources.ColumnAnnotation
	6, // 1: taxinomia.datasources.DataSource.config:type_name -> taxinomia.datasources.DataSource.ConfigEntry
	3, // 2: taxinomia.datasources.EntityTypeDefinition.urls:type_name -> taxinomia.datasources.URLTemplate
	1, // 3: taxinomia.datasources.DataSourcesConfig.annotations:type_name -> taxinomia.datasources.ColumnAnnotations
	2, // 4: taxinomia.datasources.DataSourcesConfig.sources:type_name -> taxinomia.datasources.DataSource
	4, // 5: taxinomia.datasources.DataSourcesConfig.entity_types:type_name -> taxinomia.datasources.EntityTypeDefinition
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_datasource_proto_init() }
func file_datasource_proto_init() {
	if File_datasource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datasource_proto_rawDesc), len(file_datasource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datasource_proto_goTypes,
		DependencyIndexes: file_datasource_proto_depIdxs,
		MessageInfos:      file_datasource_proto_msgTypes,
	}.Build()
	File_datasource_proto = out.File
	file_datasource_proto_goTypes = nil
	file_datasource_proto_depIdxs = nil
}
